module.exports = {
  apps: [
    {
      name: 'football-streaming',
      script: 'src/index.js',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      // Watch Node RSS only — Chromium is separate. Keep Node small on 1GB hosts.
      max_memory_restart: '350M',
      node_args: '--max-old-space-size=256 --expose-gc',
      // Prefer .env via dotenv in src/index.js; keep aligned defaults here for PM2.
      env: {
        NODE_ENV: 'production',
        TZ: 'Asia/Yangon',
        HOST: '0.0.0.0',
        PORT: 3000,
        LOW_MEMORY_MODE: 'true',
        NODE_OPTIONS: '--max-old-space-size=256 --expose-gc',
        PUPPETEER_HEADLESS: 'new',
        PUPPETEER_TIMEOUT_MS: '25000',
        PUPPETEER_BLOCK_RESOURCES: 'true',
        BROWSER_RESTART_EVERY_N_PAGES: '5',
        HIGHLIGHT_LIMIT: '8',
        MAX_STREAM_RETRIES: '1',
        SOCO_CONCURRENCY: '1',
        MYANMARTV_CONCURRENCY: '1',
        PIPELINE_CRON: '*/15 * * * *',
        HIGHLIGHT_CRON: '0 */6 * * *',
        MYANMARTV_CRON: '0 */12 * * *',
      },
      error_file: 'logs/pm2-error.log',
      out_file: 'logs/pm2-out.log',
      merge_logs: true,
      time: true,
      kill_timeout: 15000,
      listen_timeout: 10000,
      autorestart: true,
      max_restarts: 30,
      restart_delay: 10000,
    },
  ],
};
